### ISSUE TITLE
Recurring event is a week long instead of an hour long

### ISSUE THREAD

**Issue by hober** [antifraudcg/admin#1]
See [this event](https://www.w3.org/events/meetings/a42f505c-4e64-4197-a0a9-e548e7c56040/20231110T120000/) for an example. For people (like me) subscribed to our W3C calendars in a calendar program, this can be pretty annoying.

**Comment by dvorak42** [comment]
Sorry about that, looks like when I rescheduled the event I forgot to fix the start date. Should be fixed now.
